### ISSUE TITLE
Why you don't support Python3? 

### ISSUE THREAD

**Issue by pahaz** [davedash/django-fixture-magic#36]
Do you have any plan for supporting python3 ?

**Comment by abaldwin1** [comment]
+1

**Comment by davedash** [comment]
I'm not actively using this tool, so I haven't had a chance to support python3.  If someone has pull request that can support both with some minimal tests, I'd be happy to merge it.

**Comment by Dineshs91** [comment]
I needed to use in python3. So I added support. But I tested out only `dump_object`. [dineshs91/django-fixture-magic](https://github.com/Dineshs91/django-fixture-magic)

**Comment by davedash** [comment]
Want to create a pull request?

**Comment by Dineshs91** [comment]
@davedash Created a PR #46
