### ISSUE TITLE
ImportError: cannot import name loading

### ISSUE THREAD

**Issue by ncp1113** [davedash/django-fixture-magic#37]
File "/usr/local/lib/python2.7/dist-packages/fixture_magic/management/commands/dump_object.py", line 6, in <module>
    from django.db.models import loading
ImportError: cannot import name loading

I am getting the above error.  I just upgraded to django 1.9.2 and I think the problem is with django. I tried importing loading it in the shell and got the same error.

**Comment by ncp1113** [comment]
I found the source of the error.  django.db.models.loading is deprecated.  I changed the import in dump_object.py to:
try:
	from django.db.models import loading
except:
	from django.apps import apps
and further down...
try:
       dump_me = loading.get_model(app_label, model_name)
except:
	dump_me = apps.get_model(app_label, model_name)

**Comment by davedash** [comment]
Thanks @ncp1113 I'll reopen it as a reminder for myself to change this.  This code is way out of date for the new version of Django and doesn't quite support Py2 and Py3 at the same time.

**Comment by KevinGrahamFoster** [comment]
We can probably close this now that #38 is merged.
