### ISSUE TITLE
unexpected keyword argument 'use_natural_foreign_keys'

### ISSUE THREAD

**Issue by vineelyalamarthy** [davedash/django-fixture-magic#40]
I added its entry(**django-fixtur-magic**) in  "MY" requirements.txt file and also added 'fixture_magic' to the list of INSTALLED_APPS in  MY application's settings.py.  

Then I ran the command 
./manage.py dump_object hmi.odeskmenutask 1901783 > test_fixture.json. 

1901783 is its primary key.
This causes an error like this:
TypeError: **init**() got an unexpected keyword argument 'use_natural_foreign_keys'.

**Comment by gyermolenko** [comment]
hi. I got similar error and have assumed that current version of django-fixture-magic do not support my version of django (could be wrong). 
I've reinstalled app with previous version
`pip install django-fixture-magic==0.0.7`
(instead of the latest version by default ) and the error was gone.

**Comment by davedash** [comment]
@vineelyalamarthy do you still run into this issue.

**Comment by vineelyalamarthy** [comment]
No I don't.
