### ISSUE TITLE
dump_object fails to parse command arguments correctly

### ISSUE THREAD

**Issue by cb109** [davedash/django-fixture-magic#47]
The `dump_object` command is broken for me with Python 2.7, Django 1.9 on Windows 7 x64.

It falsely reads in the last argument as the `model` argument. Example:

```
$ python manage.py dump_object auth.User 1
```

will result in an options dict (see https://github.com/davedash/django-fixture-magic/blob/master/fixture_magic/management/commands/dump_object.py#L48) like:

``` python
{'ids': [],
 'kitchensink': False,
 'model': '1',
 'natural': False,
 'no_color': False,
 'pythonpath': None,
 'query': None,
 'settings': None,
 'traceback': False,
 'verbosity': 1}
```

As you can see, `ids` is empty and `model` got the id instead. It is always filled with the last argument for some reason. Maybe the parser behaviour changed from Python 2.6 to 2.7? I will try to find the reason.

A quick fix for me was to make the `model` and `id` arguments optional so I could do:

```
$ python manage.py dump_object --model=auth.User --ids=1
```

**Comment by cb109** [comment]
The root of this issue lies in some backwards compatibility code in Django versions older than 1.10. They try to mimic some `optparse` (which seemingly was the old argument parser) behaviour in regards to accepting positional arguments. This line is the culprit: https://github.com/django/django/blob/stable/1.9.x/django/core/management/base.py#L309

The issue is gone with Django 1.10+, compare this: https://github.com/django/django/blob/stable/1.10.x/django/core/management/base.py#L260

This behaviour conflicts with your `id` argument because both use `nargs='*'`. Only happens because your command overwrites the `args` class attribute (I guess you did this to provide more helpful commandline descriptions?).

Two fixes come to mind:
* Do not overwrite the `args` attribute in the `Command` class.
* Handle parser creation based on Django version and workaround the conflicting behaviour.

I will send you a pull request for the latter.

**Comment by jason-utilityapi** [comment]
@cb109 @davedash As far as I can tell, there isn't any reason to overwrite the `args` attribute in the `Command` class anymore. This is a relic of the 1.7 and earlier versions of Django. It's been completely removed from the docs for versions 1.8 and greater. Removing this line fixes the issue for Django 1.8 and 1.9:

https://github.com/davedash/django-fixture-magic/blob/master/fixture_magic/management/commands/dump_object.py#L22

**Comment by cb109** [comment]
Sounds like the best solution to me if backwards compatibility is not of concern :+1:

**Comment by jason-utilityapi** [comment]
Not really much of an issue. Anything earlier than 1.8 is no longer a supported version of Django anyway. 

1.7 has been unsupported since December of 2015. 
https://www.djangoproject.com/download/

**Comment by jason-utilityapi** [comment]
Since 1.8 is the active LTS release. It would make sense to fix this ASAP.

**Comment by davedash** [comment]
If someone can resolve the conflicts in #48 then I can merge this in and this might be closable.

**Comment by jason-utilityapi** [comment]
@davedash I have created a pull request that should resolve this. It's removing the args line since it's not needed and just creating issues in Django 1.8 and Django 1.9.

**Comment by davedash** [comment]
I think this is how fixed.
